version: '3'
services:

  #PHP Service
  mrgabricavi-laravel-app:
    image: mrgabricavi-laravel-app
    build:
      context: .
      dockerfile: Dockerfile-dev.dockerfile
    container_name: mrgabricavi-laravel-app
    restart: unless-stopped
    tty: true
    depends_on:
      - mrgabricavi-laravel-db
      - mrgabricavi-laravel-redis
    ports:
      - "8000:80"
    environment:
      SERVICE_NAME: mrgabricavi-laravel-app
      SERVICE_TAGS: dev
      PHP_IDE_CONFIG: "serverName=fpm-mrgabricavi-laravel-app"
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
      - ./_devops/local/docker/php/php-dev.ini:/etc/php8/conf.d/custom.ini:delegated

  #PostgresSQL Service
  mrgabricavi-laravel-db:
    image: postgres
    container_name: mrgabricavi-laravel-db
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: mrgabricavi-laravel-db
      POSTGRES_DB: mrgabricavi-laravel-db
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    volumes:
      - mrgabricavi_laravel_dbdata_postgres:/var/lib/postgresql/data
      - ./_devops/local/docker/postgres/dump_parking:/var/tmp/db_dumps:delegated

  #PG Admin Service
  mrgabricavi-laravel-pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    tty: true
    depends_on:
      - mrgabricavi-laravel-db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pg.io
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 8076:80
    volumes:
      - mrgabricavi_laravel_db_pgadmin_data:/var/lib/pgadmin

  #Redis Service
  mrgabricavi-laravel-redis:
    image: redis:alpine
    container_name: mrgabricavi-laravel-redis
    restart: unless-stopped
    command: redis-server --requirepass redisPass#123456
    tty: true

  #Redis Gui
  mrgabricavi-laravel-redis-gui:
    image: rediscommander/redis-commander
    container_name: mrgabricavi-laravel-redis-gui
    restart: unless-stopped
    tty: true
    depends_on:
      - mrgabricavi-laravel-redis
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=mrgabricavi-laravel-redis
      - REDIS_PASSWORD=redisPass#123456

#Volumes
volumes:
  mrgabricavi_laravel_dbdata_postgres:
    driver: local
  mrgabricavi_laravel_db_pgadmin_data:
    driver: local
